### ISSUE TITLE
Make Conan Center Index work with Qt5 and Qt6

### ISSUE THREAD

**Issue by patricia-gallardo** [turtlebrowser/turtlebrowser#71]
Making an issue to make it easier to track

**Comment by patricia-gallardo** [comment]
@ericLemanissier I've started looking into running the browser too :rofl: and I will have to debug a bit, but I'm wondering about this bit in qt.conf
````
LibraryExecutables = bin/archdatadir/bin
````

should that maybe be

````
LibraryExecutables = bin/archdatadir/libexec
````

**Comment by patricia-gallardo** [comment]
I will try to fill in the state here because I get confused
Qt5 - Windows 2019 - Release
Qt5 - Ubuntu 20.04 - Release
Qt5 - Mac 10 - Release
Qt5 - Mac 11 - Release
Qt5 - Mac 10 - Debug
Qt5 - Mac 11 - Debug (with recent XCode)

Qt6 - Windows 2019 - Release
Qt6 - Ubuntu 20.04 - Release
Qt6 - Mac 10 - Release
Qt6 - Mac 11 - Release
Qt6 - Mac 10 - Debug
Qt6 - Mac 11 - Debug (with recent XCode)

**Comment by ericLemanissier** [comment]
Qt5 Ubuntu fails to detect nss. Is the system libnss-dev package installed? Is the pkg_config_path variable set in you qt5 github action like it is in your qt6 github action?

**Comment by patricia-gallardo** [comment]
Ah, no, the workflow I'm using here is the "Update Conan" workflow, which didn't have that - added it now - I'll add new links to the above

**Comment by patricia-gallardo** [comment]
The Qt5 Mac 11 (Debug - I only have a debug build of it so far) build with new SDK needs the same patch Qt6 has

**Comment by patricia-gallardo** [comment]
Since Qt6 Mac builds are timing out I'm going to do Mac 11 with new SDK locally - I gave it a go the other day and there was an issue around CMake targets - iirc it was because QtWebEngine is in Qt6 called QtWebEngineQuick. I'm doing new builds now though, so I'll post new logs.

**Comment by patricia-gallardo** [comment]
Qt6 Windows failure seems to be this: https://bugreports.qt.io/browse/QTBUG-96533

**Comment by patricia-gallardo** [comment]
Qt5 Windows is a mystery to me - it failed after 15 minutes

**Comment by patricia-gallardo** [comment]
Qt5 Windows doesn't build in CLion for me because of the CXX thing: https://gist.github.com/patricia-gallardo/cb95187bd039be2e5df8e34dcdad64fe

**Comment by patricia-gallardo** [comment]
Building new caches locally for Qt5 (master) on Windows and Ubuntu 20.04 - it will take awhile so they will probably be ready in the morning

**Comment by ericLemanissier** [comment]
Windows qt5 error is at https://github.com/turtlebrowser/turtlebrowser/runs/4076269823?check_suite_focus=true#step:11:2186 

D:\a\turtlebrowser\turtlebrowser\release\short\cb4a06\1\qt5\qtbase\src\3rdparty\angle\src\libANGLE\renderer\d3d\d3d11\texture_format_table_autogen.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument 

This error message is sometimes associated with some file paths too long. Is there a way to make it shorter?

**Comment by patricia-gallardo** [comment]
> This error message is sometimes associated with some file paths too long. Is there a way to make it shorter?

Yes, I think so.  One minute

**Comment by patricia-gallardo** [comment]
Note to self - fix for 18.04 : remove pkgconf and install pkg-config

**Comment by patricia-gallardo** [comment]
Going to try to make a list of changes needed to the Conan Center Index (as I understand things)

- [ ] libexec in the qt.conf [link](https://github.com/turtlebrowser/turtlebrowser/issues/71#issuecomment-955177106)
- [ ] Patch missing from Qt5 recipe for MacOS11 with new SDK [link](https://github.com/turtlebrowser/turtlebrowser/issues/71#issuecomment-957254240) 
- [ ] CLion build of Qt5 (CXX is set) [link](https://github.com/turtlebrowser/turtlebrowser/issues/71#issuecomment-957771088)
- [ ] QtWebEngineQuick cmake changes needed to link [link](https://github.com/turtlebrowser/turtlebrowser/issues/71#issuecomment-957453940)

**Comment by ericLemanissier** [comment]
The second item should be solved with https://github.com/conan-io/conan-center-index/pull/7951, I think

**Comment by ericLemanissier** [comment]
Can you retry qt5 on Macos, now that the pr is merged ?

**Comment by patricia-gallardo** [comment]
> Can you retry qt5 on Macos, now that the pr is merged ?

It seems to have gotten past that error iirc - but it seems to get an error (log from local machine):
https://gist.githubusercontent.com/patricia-gallardo/d052400a589a08fdf32d36abcd685ebe/raw/348a32b22239d2b2092589ab990ca33ebfc62f89/gistfile1.txt

**Comment by ericLemanissier** [comment]
regarding the qt.conf issue. I can make a pull request on qt5 and qt6 to fix it. do you manage to start properly with only this change `LibraryExecutables = bin/archdatadir/libexec` ?

**Comment by patricia-gallardo** [comment]
> regarding the qt.conf issue. I can make a pull request on qt5 and qt6 to fix it. do you manage to start properly with only this change `LibraryExecutables = bin/archdatadir/libexec` ?

No, I don't think I managed to run yet, but I can try again. The QtWebEngineQuick cmake thing means I can't link TurtleBrowser in Qt6. I will have to try Qt5 on Linux or Windows, because Qt5 doesn't build locally on MacOS (I would have to try a different SDK).

**Comment by ericLemanissier** [comment]
the qtwebengine rename needs to be done also in the recipe, I'll made a PR for that.
LibraryExecutables seems to depend on the platform https://github.com/qt/qtbase/blob/efc1cd5799f692cfbc76bdfe1099d75141558c9b/src/corelib/global/qlibraryinfo.cpp#L500-L504, I'll make more research to confirm this.

**Comment by patricia-gallardo** [comment]
I was wrong - in Linux in Qt5 this diff is all that I need to run TurtleBrowser
LibraryExecutables = bin/archdatadir/libexec

**Comment by patricia-gallardo** [comment]
I can't test Windows for a couple of days because I'm going on a trip

**Comment by ericLemanissier** [comment]
https://github.com/ericLemanissier/turtlebrowser/actions/runs/1443988727. it's been a long time since all configuration have been green for so long. Fingers crossed it'll last until it misses disk space, or bails out after 6h....
